{{-- resources/views/public/virtual-webpage.blade.php --}}

<style>
    /* This injects the custom CSS generated by GrapesJS */
    {!! $css !!}

    /* Optional: Ensure the custom content doesn't break your layout */
    .grapes-container {
        width: 100%;
        min-height: 400px;
    }
</style>

<div class="grapes-container">
    {{-- This injects the custom HTML generated by GrapesJS --}}
    {!! $html !!}
</div>